version: '3.6'
services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
            - '5672:5672'
            - '15672:15672'
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            POSTGRES_USER: '${POSTGRES_USER}'
            POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
            POSTGRES_DB: release-queue
        ports:
            - '5432:5432'
        volumes:
            - ./data:/var/lib/postgresql/data
    server:
        container_name: server
        build: .
        ports:
            - '${PORT}:${PORT}'
        depends_on:
            - rabbitmq
            - postgres
